#!/bin/sh
# Copyright(c) 2011-2013 Shenzhen TP-LINK Technologies Co.Ltd.
# file     usbuser
# brief    
# author   Zhu Xianfeng<zhuxianfeng@tp-link.net>
# version  1.0.0
# date     29Apr14
# history  arg 1.0.0, 29Apr14, Zhu Xianfeng, Create the file. 

. /lib/functions.sh

if [ $# -ne 3 ]; then
    return
fi

local username=$1
local password=$2
local account_type=$3

local auth="$(uci_get usbshare.global.auth_all)"
local oldusername="$(uci_get usbshare.account.username)"
local oldusername1="$(uci_get usbshare.account1.username)"
local oldpassword="$(uci_get usbshare.account.password)"
local oldpassword1="$(uci_get usbshare.account1.password)"

local smbconf="/etc/samba/smb.conf.template"
local sftp_support="$(uci -q -c /etc/profile.d get profile.@sftp[0].sftp_support)"

escaped_str() {
    local word=$1

    word=${word//\\/\\\\}
    echo "${word}"
}

password=$(escaped_str "$password")

# smbpasswd
if [ ! -e /etc/samba/smbpasswd ]; then
    touch /etc/samba/smbpasswd
fi
echo "# admin = alias" > /etc/samba/smbusers
echo "" > /etc/samba/lognames.deny

#account_type = 0 : administration
#               1 : user
if [ $account_type -eq 0 ]; then
    ##ftp
    echo -e $password'\n'$password'\n' | passwd admin 1>/dev/null 2>&1
    ftp_alias stop "$oldusername" admin
    if [ "$username" != "admin" -a "$auth" = "on" ];then
        ftp_alias start "$username" admin
    fi

    ##sftp
        if [ "$sftp_support" == "yes" ];then
        if [ "$username" = "admin" ];then
            if [ "$oldusername" != "admin" ];then
                sftp_replace_user $oldusername sftpadmin 0
                sftp_alias stop $oldusername
                sftp_alias start admin
                echo -e $password'\n'$password'\n' | passwd sftpadmin 1>/dev/null 2>&1
            else
                sftp_alias stop admin
                sftp_alias start admin
            fi
        else
            if [ "$oldusername" != "admin" ];then
                sftp_replace_user $oldusername sftpadmin 0
                sftp_alias stop "$oldusername"
            else
                sftp_alias stop admin
            fi
                echo -e $password'\n'$password'\n' | passwd sftpadmin 1>/dev/null 2>&1
                sftp_replace_user sftpadmin $username 0
                sftp_alias start "$username"
        fi
    fi

    ##smbusers && smbpasswd
    echo -e $password'\n'$password'\n' | smbpasswd -s -a admin 1>/dev/console 2>&1
    if [ "$username" != "admin" -a "$oldusername1" != "guest" ]; then
        echo -e "admin = $username" > /etc/samba/smbusers
        echo -e "guest = $oldusername1" >> /etc/samba/smbusers
        echo -e "admin guest" > /etc/samba/lognames.deny
    elif [ "$username" != "admin" ]; then
        echo -e "admin = $username" > /etc/samba/smbusers
        echo -e "admin" > /etc/samba/lognames.deny
    elif [ "$oldusername1" != "guest" ]; then
        echo -e "guest = $oldusername1" > /etc/samba/smbusers
        echo -e "guest" > /etc/samba/lognames.deny
    fi
else
    ##ftp
    if [ "$auth" = "on" ];then
        echo -e $password'\n'$password'\n' | passwd guest 1>/dev/null 2>&1
    fi
    ftp_alias stop "$oldusername1" guest
    if [ "$auth" = "off" ];then
        ftp_alias start anonymous guest
    fi
    if [ "$username" != "guest" -a "$auth" = "on" ];then
        ftp_alias start "$username" guest
    fi
    
    ##sftp
    if [ "$sftp_support" == "yes" ];then
        sftp_alias stop $oldusername1

        if [ "$username" = "guest" ];then
            if [ "$oldusername1" != "guest" ];then
                sftp_replace_user $oldusername1 visit 1
                echo -e $password'\n'$password'\n' | passwd visit 1>/dev/null 2>&1
            fi
            if [ "$auth" = "on" ];then
                sftp_alias start guest
            fi
        else
            if [ "$oldusername1" != "guest" ];then
                sftp_replace_user $oldusername1 visit 1
            fi
            echo -e $password'\n'$password'\n' | passwd visit 1>/dev/null 2>&1
            sftp_replace_user visit $username 1
            if [ "$auth" = "on" ];then
                sftp_alias start $username
            fi
        fi
    fi
 
    ##smbusers && smbpasswd
    if [ "$auth" = "on" ];then
        sed -i 's/^.*map to guest = Bad User$/\#map to guest = Bad User/g' $smbconf
        echo -e $password'\n'$password'\n' | smbpasswd -s -a guest 1>/dev/console 2>&1
    fi
    if [ "$oldusername" != "admin" -a "$username" != "guest" ]; then
        echo -e "admin = $oldusername" > /etc/samba/smbusers
        echo -e "guest = $username" >> /etc/samba/smbusers
        echo -e "admin guest" > /etc/samba/lognames.deny
    elif [ "$username" != "guest" ]; then
        echo -e "guest = $username" > /etc/samba/smbusers
        echo -e "guest" > /etc/samba/lognames.deny
    elif [ "$oldusername" != "admin" ]; then
        echo -e "admin = $oldusername" > /etc/samba/smbusers
        echo -e "admin" > /etc/samba/lognames.deny
    fi
fi

if [ $account_type -eq 0 -a "$username" != "$oldusername" ]; then
    /etc/init.d/afpd stop
    /etc/init.d/avahi-daemon stop

    /usr/sbin/tm_checkrun $username
fi
