#!/bin/sh
. /lib/functions.sh
. /lib/wifi/qcawificfg80211.sh
. /lib/debug/dbg
. /lib/wifi/qca_wlan_var.sh

DEV_NUM=2

wifi_firm_info(){
	local mac=""
	local cfgMac=""
	local change_flag=""
	local wps_pin=""
	local ssid=""

	get_wlan_ini FEATURE_TRIBAND
	if [ "${FEATURE_TRIBAND}" = "y" ]; then
		DEV_NUM=3
	fi

	for i in $(seq $DEV_NUM); do
		if [ -z "$(config_get ath$(($i-1)) wps_pin)" ]; then
			if [ -z "$wps_pin" ]; then
				wps_pin="$(getfirm PIN)"
			fi
			if [ "$(config_get ath$(($i-1)) device)" = "wifi$(($i-1))" ]; then
				uci set wireless.ath$(($i-1)).wps_pin=${wps_pin}
				uci set wireless.ath$(($i-1)).encryption="psk"
				uci set wireless.ath$(($i-1)).psk_key=${wps_pin}
				uci set wireless.ath$(($i-1)).wps_state=2
				change_flag="1"
			fi
			#default security of guest network is none.
			if [ "$(config_get ath$(($i-1))1 device)" = "wifi$(($i-1))" ]; then
				uci set wireless.ath$(($i-1))1.encryption="none"
				change_flag="1"
			fi
		fi
	done
	
	local idx=0
	local mac_5g="" flag_5g2=0
	local mac="$(getfirm MAC)"

	cd /sys/class/net/
	[ -d wifi0 ] || load_qcawificfg80211
	for dev in $(ls -d wifi* 2>$STDOUT); do
		case "$(cat ${dev}/hwcaps)" in
			*11bgn) mode_11=bgn;band="2g";;
			*11abgn) mode_11=bgn;band="2g";;
			*11an) mode_11=an_5;band="5g";;
			*11an/ac) mode_11=anac_5;band="5g";;
			*11abgn/ac) mode_11=anac_5;band="5g";;
			*11bgn/ax) mode_11=bgnax;band="2g";;                              
			*11an/ac/ax) mode_11=anacax_5;band="5g";; 
		esac
		
		if [ "${FEATURE_TRIBAND}" = "y" -a "$band" = "5g" ]; then
			if [ "$flag_5g2" = "0" ]; then
				flag_5g2=1
			else
				band="5g_2"
			fi
		fi
		
		cfgMac="$(config_get wifi${idx} macaddr)"
		case $band in
			2g) mac=`mac_addr 2 $mac`;;
			5g) mac=`mac_addr 2 $mac`;;
			5g_2) mac=`mac_addr 2 $mac`;;
			*) ;;
		esac
		mac="$(echo $mac | tr 'a-f' 'A-F')"
		if [ -z "$cfgMac" ]; then
			uci set wireless.wifi${idx}.macaddr=$mac
			change_flag="1"
		elif [ "$mac" != "$cfgMac" ]; then
			uci set wireless.wifi${idx}.macaddr=$mac
			change_flag="1"
		else
			:
		fi
		if [ -z "$(config_get wifi${idx} band)" -o "$(config_get wifi${idx} band)" != ${band} ]; then
			uci set wireless.wifi${idx}.hwmode=${mode_11}
			uci set wireless.wifi${idx}.band=${band}
			change_flag="1"
			if [ -z "$ssid" ]; then
				ssid="$(getfirm SSID)"
			fi
			local suffix
			suffix=$(getfirm MAC|cut -d "-" -f 5,6 | sed 's/-//g'|tr 'a-f' 'A-F')

			if [ "${FEATURE_TRIBAND}" = "n" ]; then
				[ "$band" = "5g" ] && suffix="${suffix}_${band//g/G}"
			else
				[ "$band" = "5g" ] && suffix="${suffix}_5G-1"
				[ "$band" = "5g_2" ] && suffix="${suffix}_5G-2"
			fi
			
			if [ "$(config_get ath${idx} device)" = "wifi${idx}" ]; then
				uci set wireless.ath${idx}.ssid="${ssid}_${suffix}"
				#uci set wireless.ath${idx}.ssid="${ssid}_HOME_${band//g/G}"
			fi
			if [ "$(config_get ath${idx}1 device)" = "wifi${idx}" ]; then
				uci set wireless.ath${idx}1.ssid="${ssid}_Guest_${suffix}"
				#uci set wireless.ath${idx}1.ssid="${ssid}_GUEST_${band//g/G}"
			fi
		fi
		idx=$(($idx+1))
	done
	if [ -z "$(config_get wps model_name)" ]; then
		local model="$(getfirm MODEL)"
		uci set wireless.wps.model_name="${model}"
		change_flag="1"
	fi
	if [ -z "$(config_get wps wps_manufacturer)" -o -z "$(config_get wps wps_manufacturer_url)" ]; then
		local firm="$(getfirm FIRM)"
		local website="$(getfirm WEBSITE)"
		uci set wireless.wps.wps_manufacturer=${firm}
		uci set wireless.wps.wps_manufacturer_url=${website}
		change_flag="1"
	fi
	if [ "$change_flag" = "1" ]; then
	wifi_commit
	fi
}

config_load wireless
wifi_firm_info
