#!/bin/sh

check_wan_conn()
{	
	local res=$(sed -n '1p' /proc/driver/rtl8367s/phy)
	local count=0
	for port in ${res}
	do
			if [ $count -eq 0 ] && [ $port -eq 1 ]; then
				echo 0
				return 0
			fi
			count=$(($count+1))
	done
	
	echo 1
	return 1
}

local link=$(check_wan_conn)
[ -n "$1" ] && echo $link
return $link
